export enum EventType {
    VIEW_ITEM = 'view_item',
    CLICK_ITEM = 'click_item',
    SAVE_ITEM = 'save_item',
    ADD_TO_CART = 'add_to_cart',
    PURCHASE = 'purchase',
    SEARCH = 'search',
    GENERATE_DESIGN = 'generate_design',
    EDIT_DESIGN = 'edit_design',
    SAVE_DESIGN = 'save_design',
    MEASUREMENT_CREATED = 'measurement_created',
    MEASUREMENT_UPDATED = 'measurement_updated',
    RATE_ITEM = 'rate_item',
    RETURN_ITEM = 'return_item',
    // New types
    FEED_IMPRESSION_BATCH = 'feed_impression_batch',
    NOT_INTERESTED = 'not_interested',
    HIDE_BUSINESS = 'hide_business',
    WISHLIST_ADD = 'wishlist_add',
    WISHLIST_REMOVE = 'wishlist_remove',
}
