# fly.toml app configuration file generated for qlozet-backend on 2025-10-08T18:06:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'qlozet-backend'
primary_region = 'lhr'

[env]
  PORT = "5000"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  timeout = "5s"
  path = "/api"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
