export enum ReasonCode {
    STYLE_MATCH = 'STYLE_MATCH',
    AESTHETIC_MATCH = 'AESTHETIC_MATCH',
    TRUSTED_VENDOR = 'TRUSTED_VENDOR',
    FAST_ETA = 'FAST_ETA',
    PRICE_FIT = 'PRICE_FIT',
    FIT_COMPATIBLE = 'FIT_COMPATIBLE',
    TRENDING = 'TRENDING',
}
